

version: 2.1

jobs:
  build_texalive:
    machine: true
    parameters:
      year:
        type: string
      python:
        type: string

    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
      - run: sed 's/%$YEAR%$/<< parameters.year >>' < TexAlive_Dockerfile.template | sed 's/%$PYTHON%$/<< parameters.python >>' > Dockerfile
      - run: docker build -t $DOCKER_USERNAME/SconsTexAlive:TexAlive<< parameters.year >>Python<< parameters.year >>
      - run: docker push $DOCKER_USERNAME/SconsTexAlive:TexAlive<< parameters.year >>Python<< parameters.year >> && sleep 10

workflows:
  all_tests:
    jobs:
      - build_texalive:
          matrix:
            parameters:
              year: [
                '2017',
                '2018',
                '2019',
              ]
              python: [
                '3.9',
                '3.8',
                '3.7',
              ]